version: "3"

services:

  db:
    image: postgres:15-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./realitymod/:/opt/keycloak/themes/realitymod/
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false